version: '3.1'

services:
  db:
    image: mysql
    container_name: testmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - app-tier

  backend:
    build: .
    container_name: voting_backend
    ports:
      - "5000:5000"

    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
