version: '3.1'

services:
  db:
    image: mysql:8.0.23
    container_name: testmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - app-tier

  backend:
    build: .
    container_name: voting_backend
    command:
      - /bin/bash
      - -ce
      - |
        alembic upgrade head
        var=$$(echo 'foo')
        echo $$var
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
